# Site
repository: dingjianyun830/dingjianyu830.github.io
favicon: images/favicon.ico

# Personal info
name: Yuqi Ding
title: Research Assistant & PhD student
email: yding18@lsu.edu
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  dingjianyun830
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: yuqi-ding-a2642599
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yuqi Ding and I'm a PhD student at Lousiana State Univerisity. My advisor is Dr. Jinwei Ye.

  This is my [CV](https://www.youtube.com/watch?v=vtg4o__aRMg).

#Education Section
educaton_title: Education

#Projects Section
projects_title: Publications

#Experience Section
experience_title: Experiences

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in computational photograph some of my other interests and hobbies are:
   - Video Game Design
   - Swimming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
